name: build-and-test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    name: Checkout
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Test
      run: |
        yarn && yarn build && yarn test
